
= NEO4ART FLIES TO DALLAS AND MOVES TO THE CLOUD

== Intro

This week Neo4Art travelled to Dallas to be presented at the SpringOne 2GX 2014... etc etc etc
 

== Deploying Neo4art on Cloud Foundry

It was actually really easy! Strange to say but the hardest part was to find the link to sign up and installing the command line.


=== Signing Up

cloudfoundry.com
	Pivotal Web Services
		Sign Up for Free


=== Getting Started

*HOME*: http://docs.run.pivotal.io/starting/index.html


=== Installing the command line interface

The `cf` CLI is your primary tool for deploying and managing your applications.

*DOCS*: http://docs.run.pivotal.io/devguide/installcf/install-go-cli.html

*DOWNLOAD*: https://github.com/cloudfoundry/cli/releases

_dmg_    : https://cli.run.pivotal.io/stable?release=macosx64&version=6.6.0&source=github-rel
_binary_ : https://cli.run.pivotal.io/stable?release=macosx64-binary&version=6.6.0&source=github-rel


=== Deploying Neo4art on Cloud Foundry

*DOCS*: http://docs.run.pivotal.io/devguide/deploy-apps/deploy-app.html

This step targets the Cloud Foundry public API endpoint `api.run.pivotal.io` and establishes your connection to Pivotal Web Services.

`cf login [-a API_URL] [-u USERNAME] [-p PASSWORD] [-o ORG] [-s SPACE]`


Then you can simply

=== Deploying with CLOUD FOUNDRY MAVEN PLUG-IN:

We have many options to deploy our application. For example we could use the Cloud Foundry Maven Plugin.

*HOME*: https://spring.io/blog/2011/09/22/rapid-cloud-foundry-deployments-with-maven










cf push neo4art -p target/neo4art.war




https://console.run.pivotal.io

